# Introduction to Neuroinformatics
## Exercise session 1: Introduction to programming and jupyter

Welcome to the first exercise session of the introduction to neuroinformatics course. This exercise session will cover the very basics of python programming in jupyter notebooks. The goal in this session is to bring everyone up to the same basic level of programming. This means that this first session will probably be safe to skip for experienced programmers.

# Table of contents:

* [Packages](#packages)
* [1: Data structures](#ds)
    * [1.1: Lists](#lists)
    * [1.2: Tuples](#tuples)
    * [1.3: Dictionaries](#dicts)
    * [1.4: Sets](#sets)
* [2: Numpy](#numpy)
* [3: Pandas](#pandas)
* [4: Matplotlib for Plotting](#plotting)

# Packages <a class="anchor" id="packages"></a>

In most notebooks in this course we will use numpy for linear algebra, matplotlib to visualize and pandas for data management. These notebooks can be run online on Google Colab, or locally in a notebook. How we install packages depends on which platform we use, so we will need to check at the start of each notebook. It does not matter for this notebook, but this is a good place to get you familiar with seeing this block of code.


First, let's check our platform:

In [1]:
platform = 'notebook'
try:
    import google.colab
    platform = 'colab'
except:
    pass
print(f"platform: {platform}")

platform: colab


Next, lets make sure our packages are installed:

In [2]:
# install packages
!pip install numpy matplotlib pandas

Lastly, we import the packages we will need:

In [3]:
import numpy as np # imports numpy (which can now be called as np)
import matplotlib.pyplot as plt # imports matplotlib
import pandas as pd

---

# 1: Data Structures <a class="anchor" id="ds"></a>

Python contains 4 basic data structures:

1. Lists, which can be created using square brackets: \[\] . Lists can contain many different entries, such as numbers (1, 2...), strings (\'abcd\'), but also other lists. **Items in lists do not have to be unique**.

2. Tuples, which can be created using normal brackets: \(\). Tuples act much like lists, but are \'immutable\', meaning that **we cannot make changes to tuples**. So it's best to use Lists over Tuples if you're going to change the list later.

3. Dictionaries, which can be created with curly brackets: \{\}. Entries in dictionaries always need two objects: a so-called \'key\' and \'value\' pair. After the creating a dictionary, a value can be accessed using it's corresponding value (example below)

4. Sets, which are also created using curly brackets. But without a key:value pair. **Items in sets are unique**, so no matter how many of the same items you add to a set, it will always only contain one.

Next, we'll go over some example usages of these datastructures.

## 1.1: Lists <a class="Anchor" id="lists"></a>

Let's create a list with some brain areas:

In [4]:
# Create the list with square brackets, with the contents seperated by commas
brain_regions = ["Hippocampus", "Cortex", "Cerebellum"]

# Now we can access our brain regions by indexing in the list

# Print the first item in the list
print("First region:", brain_regions[0]) # This is known as "Zero Indexed"

# Using negative indexing, we can access the last item in the list
print("Last region:", brain_regions[-1])

# Print every item in the list seperately
print() # new line
for region in brain_regions:
    print(region)

# Finally, we can add a new item to the list using 'append'
brain_regions.append("Pons")
print("Last region after append:", brain_regions[-1])
print(f"Number of regions:", len(brain_regions)) # len() returns the number of elements in a collection

# We can select multiple items at once by using a colon
print()
print("All but the first region:", brain_regions[1:4]) # Notice element 4 is not included

# An "easier" way to select the first three items
print("First three regions:", brain_regions[:3])

First region: Hippocampus
Last region: Cerebellum

Hippocampus
Cortex
Cerebellum
Last region after append: Pons
Number of regions: 4

All but the first region: ['Cortex', 'Cerebellum', 'Pons']
First three regions: ['Hippocampus', 'Cortex', 'Cerebellum']


## 1.2: Tuples <a class="anchor" id="tuples"></a>

Let's create a tuple with some neurotransmitters:

In [5]:
# Tuple of neurotransmitters and their functions (immutable)
neurotransmitters = ("Dopamine", "Serotonin", "GABA")

# Tuples are indexed like lists
print("Second neurotransmitter:", neurotransmitters[1])

Second neurotransmitter: Serotonin


## 1.3: Dictionaries <a class="anchor" id="dicts"></a>

Let's create a dictionary with papers and some of their information:

In [6]:
# Dictionary that contains information about a paper
georgopoulos_paper = {
    'title': "Neuronal Population Coding of Movement Direction",
    'year': 1986,
    'authors': ("Apostolos P. Georgopoulos", "Andrew B. Schwartz", "Ronald E. Kettner"),
    'referenced_by': ["paper_1", "paper_2", "paper_3"]
}

# Now, whenever we wanted, we could ask this dictionary for information on the paper
print("Paper's first author:", georgopoulos_paper['authors'][0])

# We can also add new data to the dictionary
georgopoulos_paper['pmid'] = 3749885

# Now let's see what's in the dictionary
print()
print("Paper Data:", georgopoulos_paper)

# What if we want to store information on multiple papers and reviews? We can use a list for this!
moser_paper = {
    'title': "Place Cells, Grid Cells, and the Brain's Spatial Representation System",
    'year': 2008,
    'authors': ("Edvard I. Moser", "Emilio Kropff", "May-Britt Moser"),
    'referenced_by': ["paper_A", "paper_B", "paper_C"],
    'pmid': 18284371
}

# Create a list that contains both our papers
papers = [georgopoulos_paper, moser_paper]

print("\nPapers in our list:") # \n is the new line character
for paper in papers:
    print(paper['title'])

Paper's first author: Apostolos P. Georgopoulos

Paper Data: {'title': 'Neuronal Population Coding of Movement Direction', 'year': 1986, 'authors': ('Apostolos P. Georgopoulos', 'Andrew B. Schwartz', 'Ronald E. Kettner'), 'referenced_by': ['paper_1', 'paper_2', 'paper_3'], 'pmid': 3749885}

Papers in our list:
Neuronal Population Coding of Movement Direction
Place Cells, Grid Cells, and the Brain's Spatial Representation System


As you get more experience in Python, you may create what is called a **Class** to store this information, but dictionary format for storing data is commonly used in large datasets you may find yourself using one day.

## 1.4: Sets <a class="anchor" id="sets"></a>

Finally, Let's create a set with a bunch of neuroscience tasks:

In [7]:
# Set of unique cognitive tasks studied
cognitive_tasks = {"Memory task", "Motor task", "Cognitive task"}

print("All tasks:", cognitive_tasks)

# Now, let's see what a set does with a duplicate
cognitive_tasks_2 = {"Memory task", "Motor task", "Cognitive task", "Motor task"}

print("All tasks with duplicate:", cognitive_tasks_2)

# Only unique values can exist in a set. Therefore the duplicate doesn't show up.

All tasks: {'Memory task', 'Motor task', 'Cognitive task'}
All tasks with duplicate: {'Memory task', 'Motor task', 'Cognitive task'}



---

> **Assignment 1**
>
> Learning to read documentation goes a great way when working with a package or dataset for the first time. Scan through [this](https://docs.python.org/3/tutorial/datastructures.html) webpage to find information on "list comprehension" and use it to create a list that contains only even numbers from 1 - 10. You may need to look up how to tell a number is even in python, or how the range function works.


In [12]:
# Assignment 1 code here
even = []
for x in range(1,6):
  even.append(x*2)
print(even)

[2, 4, 6, 8, 10]


---

# 2: Numpy<a class="anchor" id="numpy"></a>

When using Python for science, numpy (for linear algebra) and pandas (for data management) are two popular options. Let's walk through some things that these packages can do.

## Numpy

In [13]:
# Numpy (called with np) implements many standard linear algebra operations. Matrices in Numpy are called ndarrays and can be of any dimension for complex datasets.
import numpy as np

# Create a vector of length 2, with entries drawn from a gaussian distribution
random_vector = np.random.rand(2)

# Create an identity matrix of size (2,2)
identity_matrix = np.eye(2, 2)

# Multiply the vector by the matrix using the @ symbol
multiplied = random_vector @ identity_matrix

print("random vector:", random_vector)
print("identity matrix: \n ", identity_matrix)
print("multiplied vector:", multiplied)

random vector: [0.94525112 0.17335295]
identity matrix: 
  [[1. 0.]
 [0. 1.]]
multiplied vector: [0.94525112 0.17335295]


In [14]:
# We can create random arrays as well
random_matrix = np.random.rand(2, 2, 2)

# "Typical" mathematical operations on ndarrays act element-wise
random_matrix_plus_one = random_matrix * 0.5

# If dimensions line up, then we get normal matrix operations
random_matrix_plus_ones = random_matrix + np.ones(shape=(2, 2, 2))

print("random_matrix\n", random_matrix)
print("\nrandom_matrix halved\n", random_matrix_plus_one)
print("\nrandom matrix plus ones\n", random_matrix_plus_ones)

random_matrix
 [[[0.03181699 0.66529464]
  [0.00426722 0.30333106]]

 [[0.29564806 0.77150158]
  [0.79545071 0.66580862]]]

random_matrix halved
 [[[0.0159085  0.33264732]
  [0.00213361 0.15166553]]

 [[0.14782403 0.38575079]
  [0.39772536 0.33290431]]]

random matrix plus ones
 [[[1.03181699 1.66529464]
  [1.00426722 1.30333106]]

 [[1.29564806 1.77150158]
  [1.79545071 1.66580862]]]


In [15]:
# Similar to lists, you can look at "slices" of arrays

long_array = np.arange(20).reshape(2, 2, 5)
first_axis = long_array[:, 0, 0]
second_axis = long_array[0, :, 0]
third_axis = long_array[0, 0, :]

print("long array\n", long_array)
print("\nfirst axis of long array\n", first_axis)
print("\nsecond axis of long array\n", second_axis)
print("\nthird axis of long array\n", third_axis)

long array
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

first axis of long array
 [ 0 10]

second axis of long array
 [0 5]

third axis of long array
 [0 1 2 3 4]



---

> **Assignment 2**
>
> Understanding the structure of the dataset you are working with is critical to ensure you are using the right indexing to read the right data. How would you index long_array to extract the sub-array [[6, 7, 8], [16, 17, 18]]?

In [26]:
# Assignment 2 code here
assignment_axis = long_array[:, 1, 1:4]
print(assignment_axis)

[[ 6  7  8]
 [16 17 18]]


> **Assignment 3**
>
> Read a bit about [ndarray documentation](https://numpy.org/doc/stable/reference/arrays.ndarray.html). Suppose you are given an arbitrary ndarray. What method would you use to get the dimensions (also known as shape) of the array? If you want to know how many dimensions an array has (one dimensional, two dimensional, three dimensional, etc), what function could you use to determine this programmatically? Use this method on long_array to show it is three dimensional.

In [31]:
# Assignment 3 code here
n_axis_dimensions = long_array.shape
print("dimensions of axis:", n_axis_dimensions)
n_dimension = len(n_axis_dimensions)
print("dimension of array:",n_dimension)

dimensions of axis: (2, 2, 5)
dimension of array: 3


---

## 3: Pandas

Pandas is a package that manages data in table much like software like excel.

In the next example we will create some fake neural data (sampled from the normal distribution) for 5 different neurons and store this data in a pandas 'dataframe' with timestamped information:


In [32]:
import pandas as pd

# Creating a NumPy array representing neuronal activity over time
neural_activity = np.random.rand(100, 5)  # 100 time points, 5 neurons

# Creating a Pandas DataFrame to hold this data with time as index
time_points = pd.date_range(start='2023-01-01', periods=100, freq='min')
neural_df = pd.DataFrame(neural_activity, columns=[f'Neuron_{i}' for i in range(1, 6)], index=time_points)

# Print the first 5 rows (the 'head') of the dataframe
print(neural_df.head())
print()

# Calculate mean activity of each neuron
mean_activity = neural_df.mean()
print("Mean activity of each neuron: \n", mean_activity)

                     Neuron_1  Neuron_2  Neuron_3  Neuron_4  Neuron_5
2023-01-01 00:00:00  0.949945  0.245252  0.325958  0.492838  0.765085
2023-01-01 00:01:00  0.322177  0.487094  0.811565  0.934923  0.457673
2023-01-01 00:02:00  0.915400  0.338214  0.805544  0.557990  0.176989
2023-01-01 00:03:00  0.075650  0.042251  0.971377  0.716980  0.376099
2023-01-01 00:04:00  0.081781  0.570367  0.480479  0.415957  0.982792

Mean activity of each neuron: 
 Neuron_1    0.441310
Neuron_2    0.490917
Neuron_3    0.517206
Neuron_4    0.482358
Neuron_5    0.530550
dtype: float64


---

> **Assignment 4**
>
> You can access the dataframe's columns just how you would access a dictionary! Try to extract the data of just Neuron_3.

In [ ]:
# Assignment 4 code here

---

# 4: Matplotlib for Plotting <a class="anchor" id="plotting"></a>

We will often ask you to visualize data in this course. One popular way of visualizing data in python is through the matplotlib package.

In this example we will use the data we generated in the previous example, and visualize the activity of the neurons over time, and on average per neuron:

In [ ]:
import matplotlib.pyplot as plt

# Using the neural_df DataFrame from the previous example

f, ax = plt.subplots(1, 1, figsize=(12, 6))
# Plot the activity of all neurons over time
neural_df.plot(ax=ax, kind='line')
plt.title("Neuronal Activity Over Time")
plt.xlabel("Time")
plt.ylabel("Activity Level")
plt.show()


In [ ]:

# Let's see what neuron has the most activity using a bar plot.
f, ax = plt.subplots(1, 1, figsize=(12, 6))
neural_df.mean(0).plot(ax=ax, kind='bar')
plt.title("Average neuronal Activity per Neuron")
plt.ylabel("Activity Level")
plt.show()


# Sliders for interactive usage

We will often ask you to discover properties from our models and systems by running simulations with different settings. To modify the simulations we will add sliders.

In this example we will simulate many neurons and their "spikes". This is a simple simulation that relies on a probability distribution called a **"Poisson" distribution**. Each black line indicates that the neuron is active and each white space indicates that the neuron is inactive.

With the help of the slider, you can modify the rate driving the Poisson process.

In [ ]:
from ipywidgets import interact, IntSlider
import matplotlib.gridspec as gridspec

# Function to generate spikes using a Poisson process
def generate_spikes(firing_rate, duration=1000, num_trials=50):
    # Convert firing rate from Hz to probability per ms
    spike_prob = firing_rate / 1000.0

    # Generate random spikes for each trial
    spikes = np.random.rand(num_trials, duration) < spike_prob
    return spikes

# Function to plot the raster plot
def plot_raster(firing_rate):
    duration = 1000  # Duration in ms
    num_trials = 50  # Number of trials

    spikes = generate_spikes(firing_rate, duration, num_trials)

    fig = plt.figure(figsize=(10, 6))
    gs = gridspec.GridSpec(1, 1)

    ax = fig.add_subplot(gs[0, 0])
    ax.set_title(f"Raster plot (Firing rate = {firing_rate} Hz)")
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("Trials")

    for trial in range(spikes.shape[0]):
        spike_times = np.where(spikes[trial])[0]
        ax.vlines(spike_times, trial + 0.5, trial + 1.5, color='black')

    ax.set_xlim([0, duration])
    ax.set_ylim([0, num_trials])
    plt.plot()

# Create an interactive slider to adjust the firing rate
interact(plot_raster, firing_rate=IntSlider(min=1, max=100, step=1, value=20, description="Firing rate (Hz)"));


---

> **Assignment 5**
>
> Going back to the plot with our neuron activity, it looks very messy because we have the plots for all five neurons on top of each other. Using matplotlib subplots, we can put multiple plots into one "frame". Below is the core of the code to make the plots. Take a look at [this matplotlib example page](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subplots_demo.html) on subplots to learn how to add labels and titles. If you want, you can navigate other matplotlib pages to learn about how to style your plot to your heart's content.

In [ ]:
f, ax = plt.subplots(5, 1)
plt.tight_layout()
for index, neuron_number in enumerate(neural_df):
    ax[index].plot(neural_df[neuron_number])

---

# End of this exercise session